insert into mysystem.drugs (drug_name, strength, company_id) values ('pilocarpine hydrochloride', 'super', 1);
insert into mysystem.drugs (drug_name, strength, company_id) values ('Buspirone hydrochloride', 'extreme', 4);
insert into mysystem.drugs (drug_name, strength, company_id) values ('Water', 'extreme', 10);
insert into mysystem.drugs (drug_name, strength, company_id) values ('isosorbide dinitrate', 'low', 7);
insert into mysystem.drugs (drug_name, strength, company_id) values ('Anticoagulant Citrate Phosphate Dextrose (CPD)', 'super', 6);
insert into mysystem.drugs (drug_name, strength, company_id) values ('Pyrithione Zinc', 'maximum', 5);
insert into mysystem.drugs (drug_name, strength, company_id) values ('Olanzapine', 'maximum', 7);
insert into mysystem.drugs (drug_name, strength, company_id) values ('Levetiracetam', 'low', 10);
insert into mysystem.drugs (drug_name, strength, company_id) values ('Triclosan', 'maximum', 2);
insert into mysystem.drugs (drug_name, strength, company_id) values ('Alcohol', 'maximum', 10);
insert into mysystem.drugs (drug_name, strength, company_id) values ('Oxygen', 'maximum', 4);
insert into mysystem.drugs (drug_name, strength, company_id) values ('Albuterol Sulfate', 'high', 5);
insert into mysystem.drugs (drug_name, strength, company_id) values ('Aesculus hippocastanum, Collinsonia canadensis', 'extreme', 10);
insert into mysystem.drugs (drug_name, strength, company_id) values ('Soft Cheat Brome', 'high', 4);
insert into mysystem.drugs (drug_name, strength, company_id) values ('Sodium Fluoride', 'low', 9);
insert into mysystem.drugs (drug_name, strength, company_id) values ('Lisinopril', 'extreme', 5);
insert into mysystem.drugs (drug_name, strength, company_id) values ('Zincum Aceticum, Zincum Gluconicum', 'low', 2);
insert into mysystem.drugs (drug_name, strength, company_id) values ('Avobenzone, Octinoxate, Octisalate, Oxybenzone', 'low', 8);
insert into mysystem.drugs (drug_name, strength, company_id) values ('Avobenzone, Homosalate, Octisalate, Octocrylene, Oxybenzone', 'super', 2);
insert into mysystem.drugs (drug_name, strength, company_id) values ('Tricolsan', 'super', 4);
insert into mysystem.drugs (drug_name, strength, company_id) values ('cocoa butter, phenylephrine hydrochloride', 'high', 2);
insert into mysystem.drugs (drug_name, strength, company_id) values ('ALCOHOL', 'maximum', 5);
insert into mysystem.drugs (drug_name, strength, company_id) values ('ARNICA MONTANA ROOT and TOXICODENDRON PUBESCENS SHOOT', 'low', 10);
insert into mysystem.drugs (drug_name, strength, company_id) values ('ALUMINUM ZIRCONIUM TETRACHLOROHYDREX GLY', 'maximum', 3);
insert into mysystem.drugs (drug_name, strength, company_id) values ('Hydromorphone Hydrochloride', 'maximum', 4);
insert into mysystem.drugs (drug_name, strength, company_id) values ('Mineral oil, Petrolatum, Phenylephrine HCl, Shark liver oil', 'super', 6);
insert into mysystem.drugs (drug_name, strength, company_id) values ('Titanium dioxide', 'high', 1);
insert into mysystem.drugs (drug_name, strength, company_id) values ('Melaleuca Pollen', 'super', 6);
insert into mysystem.drugs (drug_name, strength, company_id) values ('Quetiapine fumarate', 'medium', 9);
insert into mysystem.drugs (drug_name, strength, company_id) values ('Simvastatin', 'extreme', 7);
insert into mysystem.drugs (drug_name, strength, company_id) values ('Natural Medicine', 'extreme', 6);
insert into mysystem.drugs (drug_name, strength, company_id) values ('BETA VULGARIS and ASCORBIC ACID ', 'low', 2);
insert into mysystem.drugs (drug_name, strength, company_id) values ('OCTINOXATE, OXYBENZONE, TITANIUM DIOXIDE', 'high', 5);
insert into mysystem.drugs (drug_name, strength, company_id) values ('Titanium Dioxide and Zinc Oxide', 'maximum', 7);
insert into mysystem.drugs (drug_name, strength, company_id) values ('SILICON DIOXIDE and COMFREY ROOT ', 'medium', 8);
insert into mysystem.drugs (drug_name, strength, company_id) values ('Homeopathic Liquid', 'low', 9);
insert into mysystem.drugs (drug_name, strength, company_id) values ('menthol', 'medium', 3);
insert into mysystem.drugs (drug_name, strength, company_id) values ('Norethindrone', 'maximum', 5);
insert into mysystem.drugs (drug_name, strength, company_id) values ('Sodium Fluoride', 'medium', 10);
insert into mysystem.drugs (drug_name, strength, company_id) values ('tramadol hydrochloride', 'low', 10);
insert into mysystem.drugs (drug_name, strength, company_id) values ('Oxygen', 'low', 4);
insert into mysystem.drugs (drug_name, strength, company_id) values ('Phenazopyridine', 'medium', 3);
insert into mysystem.drugs (drug_name, strength, company_id) values ('Sertraline Hydrochloride', 'extreme', 6);
insert into mysystem.drugs (drug_name, strength, company_id) values ('Testes Apis', 'medium', 2);
insert into mysystem.drugs (drug_name, strength, company_id) values ('Homosalate, Octinoxate, Octisalate, Oxybenzone, and Titanium Dioxide', 'high', 3);
insert into mysystem.drugs (drug_name, strength, company_id) values ('Benzoyl Peroxide', 'super', 9);
insert into mysystem.drugs (drug_name, strength, company_id) values ('Gemcitabine Hydrochloride', 'extreme', 1);
insert into mysystem.drugs (drug_name, strength, company_id) values ('Adrenalinum', 'medium', 4);
insert into mysystem.drugs (drug_name, strength, company_id) values ('Milk Thistle, Chelidonium Majus Root, and Taraxacum Palustre Root', 'high', 10);
insert into mysystem.drugs (drug_name, strength, company_id) values ('Dextrose monohydrate', 'medium', 6);
